version: "3"

services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3000:3000"

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: EkodusVpsProjects@123TempDevServer
      MYSQL_DATABASE: besakina
      MYSQL_USER: besakina
      MYSQL_PASSWORD: Developer@123
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db-data:
