version: "3"

services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file: .env

  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file: .env

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    env_file: .env

volumes:
  db-data:
