version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: EkodusVpsProjects@123TempDevServer
      MYSQL_DATABASE: besakina
      MYSQL_USER: besakina
      MYSQL_PASSWORD: Developer@123
